# Generated by Django 4.1.3 on 2022-11-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0005_alter_fungi_options_remove_similarfungi_sfid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarfungi',
            old_name='SimilarFungiName2',
            new_name='SFid',
        ),
    ]
