# Generated by Django 4.1.3 on 2022-11-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0007_alter_similarfungi_sfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarfungi',
            name='SimilarFungiId',
        ),
    ]
