# Generated by Django 4.1.3 on 2022-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0009_remove_habitat_comments_alter_detailsources_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='Comments',
            field=models.CharField(blank=True, default='no comments', max_length=2048, null=True),
        ),
    ]
