# Generated by Django 4.1.3 on 2022-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0010_habitat_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gills',
            name='GillsPresent',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('initial', ''), ('Sex on the backseat', 'Sex on the backseat'), ('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
    ]
