# Generated by Django 4.1.3 on 2022-11-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0011_alter_gills_gillspresent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gills',
            name='GillsPresent',
            field=models.CharField(blank=True, choices=[('initial', ''), ('NoData', 'NoData'), ('Sex on the backseat', 'Sex on the backseat'), ('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PersonalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthFound', models.CharField(blank=True, choices=[('initial', ''), ('NoData', 'NoData'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Other', 'Other')], default='NoData', max_length=255, null=True, verbose_name='Month Found')),
                ('WhereFound', models.CharField(blank=True, default='NoData', max_length=2048, null=True, verbose_name='Where Found')),
                ('Environment', models.CharField(blank=True, default='NoData', max_length=2048, null=True, verbose_name='Where Found')),
                ('slug', models.SlugField(null=True)),
                ('Fungi', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='fungi_notes', to='fungi.fungi')),
            ],
            options={
                'verbose_name': 'Personal Note',
                'verbose_name_plural': 'Personal Notes',
                'db_table': 'PersonalNotes',
                'ordering': ['Fungi'],
                'managed': True,
            },
        ),
    ]
