# Generated by Django 4.1.3 on 2022-11-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0012_alter_gills_gillspresent_personalnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalnotes',
            old_name='Environment',
            new_name='EnvironmentNotes',
        ),
        migrations.RenameField(
            model_name='personalnotes',
            old_name='MonthFound',
            new_name='MonthFoundNotes',
        ),
        migrations.RenameField(
            model_name='personalnotes',
            old_name='WhereFound',
            new_name='WhereFoundNotes',
        ),
    ]
