# Generated by Django 4.1.3 on 2022-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0013_rename_environment_personalnotes_environmentnotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnotes',
            name='PersonalNotesComments',
            field=models.CharField(blank=True, default='no comments', max_length=2048, null=True, verbose_name='Comments'),
        ),
    ]
