# Generated by Django 4.1.3 on 2022-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0014_personalnotes_personalnotescomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalNotes',
        ),
    ]
