# Generated by Django 4.1.3 on 2022-11-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0018_delete_testtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTitem', models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='')),
                ('slug', models.SlugField(null=True)),
                ('Fungi', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='fungi_test', to='fungi.fungi')),
            ],
            options={
                'verbose_name': 'TestTables',
                'verbose_name_plural': 'TestTables',
                'db_table': 'TestTable',
                'ordering': ['Fungi'],
                'managed': True,
            },
        ),
    ]
