# Generated by Django 4.1.3 on 2022-11-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0019_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
