# Generated by Django 4.1.3 on 2022-11-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0021_alter_personalnotes_environmentnotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funginotes',
            name='EnvironmentNotes',
            field=models.CharField(blank=True, default='NoData', max_length=2048, null=True, verbose_name='Environment Notes'),
        ),
        migrations.AddField(
            model_name='funginotes',
            name='MonthFoundNotes',
            field=models.CharField(blank=True, choices=[('initial', ''), ('NoData', 'NoData'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Other', 'Other')], default='NoData', max_length=255, null=True, verbose_name='Month Found'),
        ),
        migrations.AddField(
            model_name='funginotes',
            name='WhereFoundNotes',
            field=models.CharField(blank=True, default='NoData', max_length=2048, null=True, verbose_name='Where Found'),
        ),
        migrations.AddField(
            model_name='funginotes',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
