# Generated by Django 4.1.3 on 2022-11-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0022_funginotes_environmentnotes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funginotes',
            options={'managed': True, 'ordering': ['Fungi'], 'verbose_name': 'Fungi Note', 'verbose_name_plural': 'Fungi Notes'},
        ),
        migrations.AlterModelTable(
            name='funginotes',
            table='FungiNotes',
        ),
        migrations.DeleteModel(
            name='PersonalNotes',
        ),
    ]
