# Generated by Django 4.1.3 on 2022-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0023_alter_funginotes_options_alter_funginotes_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funginotes',
            name='NoteCount',
            field=models.IntegerField(default=1),
        ),
    ]
